### ISSUE TITLE
document /etc/grub.d/40_qusal.cfg

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#13]
https://github.com/ben-grande/qusal/blob/main/salt/kicksecure-minimal/files/template/grub.d/40_qusal.cfg

No longer supported by upstream. It might. Maybe. But that feature is still very much in flux, unclear future upstream. Reference:

https://github.com/Kicksecure/security-misc/issues/157

**Comment by ben-grande** [comment]
I am aware the grub line is not doing anything, it is only installed with the development state `install-testing.sls`, it does not break anything, it is just never passed to the script. The systemd script is also broken because it is missing the number/level in the argument.

I will remove the grub as it became extraneous.
