### ISSUE TITLE
document /etc/hide-hardware-info.d/40_qusal.conf

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#14]
Because not a Kicksecure upstream default.

https://github.com/ben-grande/qusal/blob/main/salt/kicksecure-minimal/files/template/hide-hardware-info.d/40_qusal.conf

**Comment by ben-grande** [comment]
It is only placed in the development state:
https://github.com/ben-grande/qusal/blob/e35c9fbf4b4ca1044167acee2c431efdcb656012/salt/kicksecure-minimal/install-testing.sls#L29-L44

I understand it deviates from upstream, but it is intended for testing only. I don't plan to document everything that may break when using the testing state because it can become lengthy. If you still think it is a problem, I will set to Kicksecure's default.

**Comment by adrelanos** [comment]
It's a problem and already created a mess here. Mess as in a time consuming, difficult to debug issues. This happened quick. It already likely generated this issue (or could have generated it):
https://forums.whonix.org/t/update-torbrowser-is-currently-broken/18279

These are non-defaults for good reasons. Because there's known, not easily fixable breakage.

The user needs to be consciously aware of the opt-in features that they enabled so no time is wasted attempting to debug.
