### ISSUE TITLE
Does Qubes plan to deprecate `salt`?

### ISSUE THREAD

**Issue by adrelanos** [ben-grande/qusal#16]
Quote https://github.com/QubesOS/qubes-issues/issues/8413#issuecomment-1673184958 @marmarek

> This is standard output from salt, not specific to qubesctl (which is just a wrapper around salt). If anything, that would be a feature request to salt. But since we are moving to own updater in place of salt, I don't think such change is worth doing.

Asked there. The outcome of that seems crucial for the future of this project.

**Comment by ben-grande** [comment]
No, qubes is not moving away from salt, but the updater has moved away from salt.

There are many things that are still done with salt, such as creating all the default qubes and setting configuration for keyboard in grub directory etc. I don't see this happening without salt because it makes it very easy to debug.

**Comment by ben-grande** [comment]
https://github.com/QubesOS/qubes-issues/issues/8413#issuecomment-1921882886
