### ISSUE TITLE
fedora-minimal misses python3-urllib3

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#38]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

[81bf77c](https://github.com/ben-grande/qusal/commit/81bf77cabeb84cee9925943696f332c6344deea2)

### Brief summary

Followed BOOTSTRAP.md to install dom0 requirements in order defined there. 
fedora-minimal fails with python3-urrllib3 missing

### Steps to reproduce

deploy dom0, debian-minimal, fedora-minimal, sys-cacher and then mgmt
fedora-minimal fails while mgmt succeeds (later install missing dep of the former)

### Expected behavior

BOOTSTRAP defined steps should work as described.
Just deployed clean on freshly received nv41 for testing clean.

### Actual behavior

Fails at fedora-minimal. mgmt deploys the missing dep?

**Comment by ben-grande** [comment]
I though I had fixed it in https://github.com/ben-grande/qusal/commit/b240ad6c5e59c276432397a5fe22b4fbd75dd2fd. Relevant issue:
- https://github.com/ben-grande/qusal/issues/28

But now I see the problem, that change should have partially been made to `fedora-minimal` and not to `mgmt` entirely. Thanks for reporting.

**Comment by ben-grande** [comment]
It affects everyone that has installed fedora-minimal already, but after the following Marek's commit reachs the stable template: https://github.com/QubesOS/qubes-builder-rpm/commit/fa42621395a89eceacdcc701c3a672df33791b63, it will not apply for future template installs. But reinstalling a template is not common unfortunately so I will have to keep that workaround for some time.

**Comment by tlaurion** [comment]
Changing bootstrap dependencies order to deploy dom0 and then mgmt could be
a woraround AFAIK.

Also not trusting creation worked and checking if parent fedora-minimal
contains the requirements?

**Comment by ben-grande** [comment]
> Changing bootstrap dependencies order to deploy dom0 and then mgmt could be a woraround AFAIK.

I didn't make it clear in the bootstrap guide, the order of the formulas does not matter for them to work, but applying in the specified order gives the best results:

- Dom0 first because it set global preferences;
- Templates early to update them before other formulas clone them;
- Cacher early to start caching packages when possible; and
- Mgmt early to have a faster Salt runtime, as the minimal template boots faster.

You can do it in any order, I am just recommending this order for the best experience. If you don't install and update templates early, and cache packages, and minimal mgmt dvm, you will have to spend more time updating and longer runtime overall.

> Also not trusting creation worked and checking if parent fedora-minimal contains the requirements?

Possible but requires:

1. Check if template `tpl-qubes-builder` exists (depends on fedora-minimal):
1.1. If it doesn't exist, starting `fedora-minimal` and check if it has dependency `python3-urllib3`. If it doesn't, install and shut it down, if it has, shutdown and clone template.
1.2 If template exists, guarantee it has python3-urrlib3

I think I will settle to install `python3-urllib3` for every template that depends on `fedora-minimal` (`1.2) so it is always present and I don't need to check the base template every time.

**Comment by ben-grande** [comment]
One thing also is that to target `fedora-39-minimal`, you need to have a `fedora-39` (full) present and as the `management_dispvm`, that is unfortunately, necessary. As `mgmt` depends on `fedora-minimal`, it also depends on `fedora`, so this order is necessary.
