### ISSUE TITLE
Disp-sys-audio not configured to start automatically on boot

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#39]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

Latest

### Brief summary

All qubes setuped to depend on sys-audio but sys-audio not setup to boot automatically nor any qube starting it

### Steps to reproduce

Deploy sys-audio

### Expected behavior

Have pci device removed from dom0 and pass-through sys-audio on boot as well as all Bluetooth controller (but not possible by default. Notes should be added in sys-audio notes) 

### Actual behavior

Audio still on dom0 unless sys-audio manually started. More troubleshooting needed, will comment later

**Comment by ben-grande** [comment]
> Disp-sys-audio not configured to start automatically on boot

That is true. As of now, it is necessary to restart pipewire on the client for sys-audio to work, to solve this, it depends on upstream changes:

- https://github.com/QubesOS/qubes-issues/issues/8975

In the future, it won't be necessary and it won't need to autostart, if you need audio, you just start the qube and the audio will work, or streaming audio will make in some way qrexec trigger the audiovm to be started.

Do you have strong reasons why it should be the default state `create.sls` instead of a new optional state `autostart.sls`?

**Comment by tlaurion** [comment]
> Do you have strong reasons why it should be the default state create.sls instead
of a new optional state autostart.sls?

Nope.
