### ISSUE TITLE
Sys-cacher depends on browser.install-common which is not found

### ISSUE THREAD

**Issue by tlaurion** [ben-grande/qusal#40]
### Commitment

I confirm that I have read the following resources:

- [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
- [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
- [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
- [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

Latest 

### Brief summary

sys-cacher depends on browser which depends on browser-installed-chromium which depdends on browser.install-common which is not found

### Steps to reproduce

Deploy sys-cacher after dom0, debian-minimal and fedors-minimal

### Expected behavior

sys-cacher deployed successfully

### Actual behavior

Half baked deployment requiring deinit to revert. browser is installed but doesn't talk to cacher through 8082 and updates cannot be downloaded. Also default uodatevm not changed in global config.

**Comment by ben-grande** [comment]
>  browser is installed but doesn't talk to cacher through 8082 and updates cannot be downloaded.

If `browser.install-common` failed, this won't work because the file `browser/install-common.sls` pulls `qubes-core-agent-networking` which has `socat` which is a dependency of `qvm-connect-tcp` which is called by `browser/files/browser/rc.local.d/50-sys-cacher.rc` to be able to connect on boot to `sys-cacher` port `8082`.

>  updates cannot be downloaded

If the installation failed, there is a possibility that other things have failed midway. I can't diagnose the problem based on this. Can you please share more information of the commands that you ran an failed? Rerun the installation steps after I push the commit to fix the browser.install-common, which I already detected.

> Also default uodatevm not changed in global config.

The cacher doesn't changes `qubes-prefs updatevm`. That setting is only used by dom0 updates via `qubes-dom0-update`, `qvm-template` etc. Because the cacher doesn't cache dom0, doesn't make sense to make it the global updatevm.

The updatevm setting can be changed by `sys-mirage-firewall`, `sys-firewall` and `sys-pihole`, in other words, the firewall qubes, that are always on when network connections are needed.

**Comment by ben-grande** [comment]
I will be rerunning completely the `sys-cacher` formula to see if there is any more problems on its installation and usage.

**Comment by ben-grande** [comment]
I can complete the cacher installation successfully and open the GUI page of cacher on sys-cacher-browser successfully also. Updates on templates and non-templates also work.

About updates that cannot be downloaded, I would need more information on this regard, but this is for another issue, as this one focused on `browser.install-common`.
