### ISSUE TITLE
Unable to find package markdowlint in dev formula

### ISSUE THREAD

**Issue by wassp-ds** [ben-grande/qusal#90]
### Commitment

I confirm that I have read the following resources:

*   [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
*   [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
*   [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
*   [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
*   [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Software version

R4.2.1

### Brief summary

Fixed typo in `install.sls`: `markdowlint` -> `markdownlint` - still crashes.

### Steps to reproduce

`sudo qubesctl --skip-dom0 --targets=tpl-dev state.apply dev.install`
`E: Unable to locate package markdowlist`

### Actual behavior

EDIT: after the fix the package is still not found, causing the installation to crash.

.

**Comment by ben-grande** [comment]
Thanks for the report. That happens because the program name is `mdl`, the package name is `ruby-mdl` and the project name is [markdownlint](https://github.com/markdownlint/markdownlint). Also because I thought it is just a simple edit that it won't break, but this was just proven false and build CI would help me not deliver such issue to users... Commit coming soon.
