### ISSUE TITLE
video-companion formula and persistent attachment of mics/webcams

### ISSUE THREAD

**Issue by kennethrrosen** [ben-grande/qusal#92]
### Commitment

I confirm that I have read the following resources:

*   [How to troubleshoot Qusal](https://github.com/ben-grande/qusal/blob/main/docs/TROUBLESHOOT.md)
*   [How to ask questions The Smart Way](http://catb.org/esr/faqs/smart-questions.html)
*   [Writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/)
*   [Question checklist](https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/)
*   [Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)

### Question

With video-companion, is it unadvisable to --persistent attach the user's mic and webcams to the client? 

Thank you!

.

**Comment by ben-grande** [comment]
> With video-companion, is it unadvisable to --persistent attach the user's mic and webcams to the client?

Yes, it is inadvisable and unnecessary.

There is no need to attach mic to the client once you have an AudioVM. Some Webcams have integrated microphone though, this is a different case.

There is only one case when it can be required, when you want to use both (mic/webcam) from the same client at the same time, which is not uncommon in case you are doing a video call and talking and wants to share screen:

- https://github.com/QubesOS/qubes-issues/issues/9272

But if you attach the mic to the AudioVM (which I couldn't get my integrated mic to work):

- https://github.com/QubesOS/qubes-issues/issues/8560

But I got USB headset with microphone attached to AudioVM to work.

It is unadvisable because those devices can compromise the client by being on the same qube, but if they are isolated, the risk is lower.

Try this setup:

1. From dom0, attach mic to AudioVM, configure the input device using Pavucontrol or Easyeffects or via command-line to the use the attached microphone.
2. Set audio client audiovm to the wanted AudioVM, be it dom0 or disp-sys-audio.
3. From audio client, run `qubes-video-companion webcam` and target the USBVM that holds the webcam.

Try to use a video conference application to test if everything is working. You can use `cheese` for the webcam test, I don't remember if it covers sound. You can use the browser with Jitsi, or online sites to do microphone, speaker, webcam test also (may contain ads and not respect your privacy) or do a Signal call or Element with yourself if you have 2 accounts.

**Comment by ben-grande** [comment]
Closing as there was no further discussion.
